## Indian data set with Missing values tutorial && PCA

**Tutorials used in this notebook**

https://machinelearningmastery.com/handle-missing-data-python/

https://plot.ly/ipython-notebooks/principal-component-analysis/

**Jupyter Notebooks**

https://www.packtpub.com/books/content/basics-jupyter-notebook-and-python

https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/

**Plotly**

https://images.plot.ly/plotly-documentation/images/python_cheat_sheet.pdf

https://plot.ly/python/line-and-scatter-plots-tutorial/

https://plot.ly/python/offline/

https://plot.ly/python/ipython-notebook-tutorial/

**Markdown** <br>
http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

http://datascience.ibm.com/blog/markdown-for-jupyter-notebooks-cheatsheet/


#### Installations
from the Anaconda prompt
conda install -c plotly plotly

#### Hints to get plotly to work
- Do a hard reload to get the plots to load properly.

jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10





In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def PrintMatrixByRows(matrix, rows, name):
    print("The shape of matrix: ", name, matrix.shape)
    cnt = rows
    if cnt > matrix.shape[0]:
        cnt = matrix.shape[0]
    
    print("The first", cnt, "of matrix:", name)

    for i in range(cnt):
        print(*matrix[i,:],  sep=" ")
        #X[i,:])  print ["{0:0.2f}".format  "insert into users values(%s, \'%s\', ...);" % array)
    
def PrintVector(vector, rows, name):
    print("The shape of vector: ", name, vector.shape)   
    cnt = rows
    
    if cnt > vector.shape[0]:
        cnt = vector.shape[0]
    
    print("The first", cnt,"of vector:", name)
    
    for i in range(cnt):
     print(vector[i])


#### Read dataset and clean up

In [3]:
data = {}
Headers = ["PCnt", "PlasmaGConc", "BP", "TricepsSFThick", "2HrSerumInsulin", "BMI", "DiabetesPFunc", "Age", "Outcome"]
d = pandas.read_csv("C:\\Users\\bzelasky\\Tutorials\\Indians.csv", names= Headers)
print(d.head(20))

    PCnt  PlasmaGConc  BP  TricepsSFThick  2HrSerumInsulin   BMI  \
0      6          148  72              35                0  33.6   
1      1           85  66              29                0  26.6   
2      8          183  64               0                0  23.3   
3      1           89  66              23               94  28.1   
4      0          137  40              35              168  43.1   
5      5          116  74               0                0  25.6   
6      3           78  50              32               88  31.0   
7     10          115   0               0                0  35.3   
8      2          197  70              45              543  30.5   
9      8          125  96               0                0   0.0   
10     4          110  92               0                0  37.6   
11    10          168  74               0                0  38.0   
12    10          139  80               0                0  27.1   
13     1          189  60              23       

Inspect data for missing values

In [4]:
d.isnull().sum()

PCnt               0
PlasmaGConc        0
BP                 0
TricepsSFThick     0
2HrSerumInsulin    0
BMI                0
DiabetesPFunc      0
Age                0
Outcome            0
dtype: int64

Basic stats of the data

In [5]:
print(d.describe())

             PCnt  PlasmaGConc          BP  TricepsSFThick  2HrSerumInsulin  \
count  768.000000   768.000000  768.000000      768.000000       768.000000   
mean     3.845052   120.894531   69.105469       20.536458        79.799479   
std      3.369578    31.972618   19.355807       15.952218       115.244002   
min      0.000000     0.000000    0.000000        0.000000         0.000000   
25%      1.000000    99.000000   62.000000        0.000000         0.000000   
50%      3.000000   117.000000   72.000000       23.000000        30.500000   
75%      6.000000   140.250000   80.000000       32.000000       127.250000   
max     17.000000   199.000000  122.000000       99.000000       846.000000   

              BMI  DiabetesPFunc         Age     Outcome  
count  768.000000     768.000000  768.000000  768.000000  
mean    31.992578       0.471876   33.240885    0.348958  
std      7.884160       0.331329   11.760232    0.476951  
min      0.000000       0.078000   21.000000    0.00

In [6]:
Measurements = ["PCnt", "PlasmaGConc", "BP", "TricepsSFThick", "2HrSerumInsulin", "BMI", "DiabetesPFunc", "Age"]
print((d[Measurements] == 0).sum())

PCnt               111
PlasmaGConc          5
BP                  35
TricepsSFThick     227
2HrSerumInsulin    374
BMI                 11
DiabetesPFunc        0
Age                  0
dtype: int64


Replace zeros with NAN so they will be ignored by sum, count and other operations.

In [7]:
dNew = d.copy(deep=True)
dNew[Measurements] = dNew[Measurements].replace(0, np.NaN)
print("Zero count after missing value replacement")
print((dNew[Measurements] == 0).sum())

print("\n")
print("Isnull count after missing value replacement")
dNew.isnull().sum()

Zero count after missing value replacement
PCnt               0
PlasmaGConc        0
BP                 0
TricepsSFThick     0
2HrSerumInsulin    0
BMI                0
DiabetesPFunc      0
Age                0
dtype: int64


Isnull count after missing value replacement


PCnt               111
PlasmaGConc          5
BP                  35
TricepsSFThick     227
2HrSerumInsulin    374
BMI                 11
DiabetesPFunc        0
Age                  0
Outcome              0
dtype: int64

### Remove rows with missing values

##### TBD: Another approach - Substitute something for missing values

In [8]:
X = dNew.iloc[:,0:8].values
y = dNew.iloc[:,8].values
PrintMatrixByRows(X, 5, "X")
PrintVector(y, 5, "y")

The shape of matrix:  X (768, 8)
The first 5 of matrix: X
6.0 148.0 72.0 35.0 nan 33.6 0.627 50.0
1.0 85.0 66.0 29.0 nan 26.6 0.351 31.0
8.0 183.0 64.0 nan nan 23.3 0.672 32.0
1.0 89.0 66.0 23.0 94.0 28.1 0.167 21.0
nan 137.0 40.0 35.0 168.0 43.1 2.288 33.0
The shape of vector:  y (768,)
The first 5 of vector: y
1
0
1
0
1


### Drop rows with missing values

In [9]:
print("Original dataset shape", d.shape, "Missing value shape", dNew.shape)

dNew.dropna(inplace=True)
print("Shape after missing values dropped", dNew.shape)

print("\n")
print("Isnull count after missing values dropped")
dNew.isnull().sum()

Original dataset shape (768, 9) Missing value shape (768, 9)
Shape after missing values dropped (336, 9)


Isnull count after missing values dropped


PCnt               0
PlasmaGConc        0
BP                 0
TricepsSFThick     0
2HrSerumInsulin    0
BMI                0
DiabetesPFunc      0
Age                0
Outcome            0
dtype: int64

### PCA

Eigendecomposition - Computing Eigenvectors and Eigenvalues
The eigenvectors and eigenvalues of a covariance (or correlation) matrix represent the "core" of a PCA: The eigenvectors (principal components) determine the directions of the new feature space, and the eigenvalues determine their magnitude. In other words, the eigenvalues explain the variance of the data along the new feature axes.

1) Split the Data Table in to an X matrix and y vector identifier  -- these are arrays now not dataframes

2) Standardize the data

3) Compute either eigen vectors and eigen values - use either the classic approach to perform the eigendecomposition on the covariance matrix or SVD


** Plot Histograms  **

In [10]:
# Step 1: Split the data 

X = dNew.iloc[:,0:8].values
y = dNew.iloc[:,8].values

PrintMatrixByRows(X, 5, "X") 
PrintVector(y, 5, "y")


The shape of matrix:  X (336, 8)
The first 5 of matrix: X
1.0 89.0 66.0 23.0 94.0 28.1 0.167 21.0
3.0 78.0 50.0 32.0 88.0 31.0 0.248 26.0
2.0 197.0 70.0 45.0 543.0 30.5 0.158 53.0
1.0 189.0 60.0 23.0 846.0 30.1 0.398 59.0
5.0 166.0 72.0 19.0 175.0 25.8 0.587 51.0
The shape of vector:  y (336,)
The first 5 of vector: y
0
1
1
1
1


In [2]:



#import plotly
#print(plotly.__version__)    
#plotly.offline.init_notebook_mode()

from plotly import __version__
print(__version__) # requires version >= 1.9.0
import plotly
from plotly.offline import download_plotlyjs, plot, iplot, init_notebook_mode

init_notebook_mode(connected=True)

from plotly.graph_objs import *
import plotly.tools as tls

#### note #### sometimes have to do a hard reload to ploty to work .... 

#%matplotlib inline
#import matplotlib
#import matplotlib.pyplot as plt


2.1.0


In [12]:
traces = []

legend = {0:False, 1:False, 2:False, 3:True}

result = {0: 'rgb(31, 119, 180)', 
          1: 'rgb(255, 127, 14)' }

for col in range(4):
    for key in result:     
        traces.append(Histogram(x=X[y==int(key), col], 
                        opacity=0.75,
                        xaxis='x%s' %(col+1),
                        marker=Marker(color=result[key]),
                        name=key,
                        showlegend=legend[col]))
        
data = Data(traces)


layout = Layout(barmode='overlay',
                xaxis=XAxis(domain=[0, 0.25], title='Pregnancy #'),
                xaxis2=XAxis(domain=[0.3, 0.5], title=' Plasma glucose conc'),
                xaxis3=XAxis(domain=[0.55, 0.75], title='Diastolic BP'),
                xaxis4=XAxis(domain=[0.8, 1], title='Triceps SF thickness'),
                yaxis=YAxis(title='Standardized Measure'),
                title='First Four Features of Indian Diabetes Data Set')

fig = Figure(data=data, layout=layout)

#py.iplot(fig, filename='overlaid histogram')
plotly.offline.iplot(fig)

In [13]:
traces = []

legend = {0:False, 1:False, 2:False, 3:True}

result = {0: 'rgb(31, 119, 180)', 
          1: 'rgb(255, 127, 14)' }

for col in range(4, 8):
    for key in result:     
        
        traces.append(Histogram(x=X[y==int(key), col], 
                        opacity=0.75,
                        xaxis='x%s' %(col+1 - 4),
                        marker=Marker(color=result[key]),
                        name=key,
                        showlegend=legend[col - 4]))
        
data = Data(traces)


layout = Layout(barmode='overlay',
                xaxis=XAxis(domain=[0, 0.25], title='2HrSerumInsulin'),
                xaxis2=XAxis(domain=[0.3, 0.5], title='BMI'),
                xaxis3=XAxis(domain=[0.55, 0.75], title='DiabetesPFunc'),
                xaxis4=XAxis(domain=[0.8, 1], title='Age'),
                yaxis=YAxis(title='Standardized Measure'),
                title='Second Four Features of Indian Diabetes Data Set')

fig = Figure(data=data, layout=layout)

plotly.offline.iplot(fig)

** Standardize the Data  **

Whether to standardize the data prior to a PCA on the covariance matrix depends on the measurement scales of the original features. Since PCA yields a feature subspace that maximizes the variance along the axes, it makes sense to standardize the data, especially, if it was measured on different scales  Transform the data onto unit scale (mean=0 and variance=1), which is a requirement for the optimal performance of many machine learning algorithms.

In [14]:
# Step 2: Standardize the data

from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

PrintMatrixByRows(X, 5, "X")
PrintMatrixByRows(X_std, 5, "X")


The shape of matrix:  X (336, 8)
The first 5 of matrix: X
1.0 89.0 66.0 23.0 94.0 28.1 0.167 21.0
3.0 78.0 50.0 32.0 88.0 31.0 0.248 26.0
2.0 197.0 70.0 45.0 543.0 30.5 0.158 53.0
1.0 189.0 60.0 23.0 846.0 30.1 0.398 59.0
5.0 166.0 72.0 19.0 175.0 25.8 0.587 51.0
The shape of matrix:  X (336, 8)
The first 5 of matrix: X
-0.906964389491 -1.08266285018 -0.343787048417 -0.553386656693 -0.517268200269 -0.660052317177 -1.07488093371 -1.0376752843
-0.270763899159 -1.44051671301 -1.63985939925 0.325983416791 -0.567858249837 -0.204011065062 -0.827326864284 -0.55887976724
-0.588864144325 2.4308114395 -0.0197689607084 1.59618463405 3.26855384239 -0.282638867151 -1.10238694142 2.02661602491
-0.906964389491 2.17055408471 -0.829814179981 -0.553386656693 5.82335134557 -0.345541108822 -0.368893402391 2.60117064539
0.365436591173 1.42231418969 0.142240083146 -0.944217800464 0.165697468897 -1.02174020679 0.208732759593 1.83509781808


** Calculate the covariance matrix and the eigan vectors and values **

There are three different ways to do this (see https://plot.ly/ipython-notebooks/principal-component-analysis/)

All three approaches yield the same eigenvectors and eigenvalue pairs:<br>
-  Eigendecomposition of the covariance matrix after standardizing the data.
-  Eigendecomposition of the correlation matrix.
-  Eigendecomposition of the correlation matrix after standardizing the data.


In [15]:
# Step 3: Calculate the covariance matrix and then eigan vectors and values

# Covariance matrix - a more verbose way:
#import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat1 = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
#print('Covariance matrix \n%s' %cov_mat1)

# Covariance matrix - use  numpy cov function:
cov_mat = np.cov(X_std.T)
#print('NumPy covariance matrix: \n%s' %np.cov(X_std.T))

# eigen vectors & values
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.37052395 -0.49432583 -0.18309769 -0.19646409 -0.3070832   0.57185648
   0.32587163  0.13681677]
 [-0.40962415 -0.01576903  0.4739915   0.27545294  0.06896888 -0.02794034
   0.3282308  -0.64664078]
 [-0.329302   -0.15531569 -0.3024605   0.10594172  0.8560606   0.11070909
  -0.12780073  0.05746256]
 [-0.36307415  0.43493406 -0.35992502  0.0070806  -0.27825883  0.26363882
  -0.52859778 -0.35080529]
 [-0.35200417  0.18060756  0.57101809  0.24148127 -0.035601    0.18936383
  -0.27314578  0.58937629]
 [-0.35433385  0.49117053 -0.33964674  0.0833469  -0.07174832 -0.3161217
   0.56600097  0.29232613]
 [-0.14687091  0.25744844  0.2786875  -0.8878685   0.20598539  0.01113787
   0.03872524 -0.04602574]
 [-0.42851714 -0.44939452 -0.0411173  -0.14381715 -0.20452442 -0.67418242
  -0.30636289  0.04281621]]

Eigenvalues 
[ 2.71917726  1.40043368  1.20138874  0.92011871  0.74159122  0.29792781
  0.34757108  0.3956721 ]


In [16]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs


[(2.7191772591236183,
  array([-0.37052395, -0.40962415, -0.329302  , -0.36307415, -0.35200417,
         -0.35433385, -0.14687091, -0.42851714])),
 (1.4004336777869546,
  array([-0.49432583, -0.01576903, -0.15531569,  0.43493406,  0.18060756,
          0.49117053,  0.25744844, -0.44939452])),
 (1.2013887373344203,
  array([-0.18309769,  0.4739915 , -0.3024605 , -0.35992502,  0.57101809,
         -0.33964674,  0.2786875 , -0.0411173 ])),
 (0.92011870717210831,
  array([-0.19646409,  0.27545294,  0.10594172,  0.0070806 ,  0.24148127,
          0.0833469 , -0.8878685 , -0.14381715])),
 (0.74159121531375805,
  array([-0.3070832 ,  0.06896888,  0.8560606 , -0.27825883, -0.035601  ,
         -0.07174832,  0.20598539, -0.20452442])),
 (0.29792781123937756,
  array([ 0.57185648, -0.02794034,  0.11070909,  0.26363882,  0.18936383,
         -0.3161217 ,  0.01113787, -0.67418242])),
 (0.34757108486209565,
  array([ 0.32587163,  0.3282308 , -0.12780073, -0.52859778, -0.27314578,
          0.566000

** Singular Vector Decomposition  **

While the eigendecomposition of the covariance or correlation matrix may be more intuitiuve, 
most PCA implementations perform a Singular Vector Decomposition (SVD) to improve the computational efficiency. 

In [17]:
# Step 3: SVD
u,s,v = np.linalg.svd(X_std.T)
u
s
v




array([[  6.99817831e-02,   5.78242532e-02,  -1.02959725e-01, ...,
          6.69108681e-02,  -8.31669640e-02,   2.32707214e-02],
       [ -2.31284488e-03,  -1.79336285e-02,  -9.55727997e-03, ...,
         -2.09681902e-02,   8.02050131e-02,   5.15270272e-02],
       [ -1.85441711e-02,  -3.57452689e-02,   1.12819202e-01, ...,
         -1.19881482e-02,  -9.17001984e-02,  -1.96491654e-03],
       ..., 
       [ -2.80406444e-02,  -6.22158043e-02,  -1.74987342e-02, ...,
          9.89123802e-01,   7.90664059e-03,   5.49587123e-04],
       [  8.97967549e-02,  -5.94077348e-02,  -3.84226119e-02, ...,
          8.94266453e-03,   9.40004539e-01,   1.50709909e-03],
       [  1.35536759e-02,  -1.61969831e-02,   2.66824172e-03, ...,
         -3.66559623e-04,   3.27776710e-04,   9.93925308e-01]])

**Selecting Principal Components**
The typical goal of a PCA is to reduce the dimensionality of the original feature space by projecting it onto a smaller subspace, where the eigenvectors will form the axes. However, the eigenvectors only define the directions of the new axis, since they have all the same unit length 1, which can confirmed by the following two lines of code:

In [18]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


** Rank Eigenvalues **

In order to decide which eigenvector(s) can dropped without losing too much information for the construction of lower-dimensional subspace, inspect the corresponding eigenvalues: 

The eigenvectors with the lowest eigenvalues bear the least information about the distribution of the data; those are the ones can be dropped.

In order to do so, the common approach is to rank the eigenvalues from highest to lowest in order choose the top kk eigenvectors.

In [19]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
2.71917725912
1.40043367779
1.20138873733
0.920118707172
0.741591215314
0.395672104183
0.347571084862
0.297927811239


** Explained Variance **

Calculated from the eigenvalues - the explained variance tells how much information (variance) can be attributed to each of the principal components.

In [20]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = Bar(
        x=['PC %s' %i for i in range(0,8)],
        y=var_exp,
        showlegend=False)

trace2 = Scatter(
        x=['PC %s' %i for i in range(0,8)], 
        y=cum_var_exp,
        name='cumulative explained variance')

data = Data([trace1, trace2])

layout=Layout(
        yaxis=YAxis(title='Explained variance in percent'),
        title='Explained variance by different principal components')

fig = Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

The first two principal components explain approx. 53% of the variance, the first three about 66% and the first four 77% 

** Projection Matrix ** <br>
The construction of the projection matrix will transform the data into a new new feature subspace. This is basically just a matrix of our concatenated top k eigenvectors.

Reducing a 8-dimensional feature space to a 4(???) -dimensional feature subspace, by choosing the top eigenvectors with the highest eigenvalues to construct ** d x k ** dimensional eigenvector matrix ** W **

In [21]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(8,1), 
                      eig_pairs[1][1].reshape(8,1), 
                      eig_pairs[2][1].reshape(8,1),
                      eig_pairs[3][1].reshape(8,1),
                      eig_pairs[4][1].reshape(8,1)))

# this is code for the top five but something isn't working - look at top 2 for now
                    

print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.37052395 -0.49432583 -0.18309769 -0.19646409 -0.3070832 ]
 [-0.40962415 -0.01576903  0.4739915   0.27545294  0.06896888]
 [-0.329302   -0.15531569 -0.3024605   0.10594172  0.8560606 ]
 [-0.36307415  0.43493406 -0.35992502  0.0070806  -0.27825883]
 [-0.35200417  0.18060756  0.57101809  0.24148127 -0.035601  ]
 [-0.35433385  0.49117053 -0.33964674  0.0833469  -0.07174832]
 [-0.14687091  0.25744844  0.2786875  -0.8878685   0.20598539]
 [-0.42851714 -0.44939452 -0.0411173  -0.14381715 -0.20452442]]


** Projection Onto the New Feature Space ** <br>

Use the 8 x 5 dimensional projection matrix ** W ** to transform samples onto the new subspace via the equation ** Y = X x W ** 

** Y ** is a ?? x 8 matrix of our samples.


In [22]:
Y = X_std.dot(matrix_w)
print("# rows of Y: ", len(Y), "# of cols of Y:",  len(Y[0]))

# rows of Y:  336 # of cols of Y: 5


** Plot first two principal compponents **

?? I want to look at four -- how???

In [23]:
traces = []

for outcome in (0, 1):

    trace = Scatter(
        x=Y[y==outcome,0],
        y=Y[y==outcome,1],
        mode='markers',
        name=outcome,
        marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))
    traces.append(trace)


data = Data(traces)
layout = Layout(showlegend=True,
                scene=Scene(xaxis=XAxis(title='PC1'),
                yaxis=YAxis(title='PC2'),))

fig = Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

## PCA in scikit-learn  ##

In [31]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=2)
Y_sklearn = sklearn_pca.fit_transform(X_std)

In [32]:
traces = []

for outcome in (0, 1):

    trace = Scatter(
        x=Y_sklearn[y==outcome,0],
        y=Y_sklearn[y==outcome,1],
        mode='markers',
        name=outcome,
        marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))
    traces.append(trace)


data = Data(traces)
layout = Layout(showlegend=True,
                scene=Scene(xaxis=XAxis(title='PC1'),
                yaxis=YAxis(title='PC2'),))

fig = Figure(data=data, layout=layout)
plotly.offline.iplot(fig)